version: '3.8'

services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: .
    environment:
      - MONGODB_URI=mongodb://mongo:27017/org-tree
      - JWT_SECRET=secret
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    command: ["sh", "entrypoint.sh"]

volumes:
  mongo_data:
