version: '3.8'

services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: .
    env_file: .env
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    # Only for development purposes, if deployed should be removed, or separate docker-compose created
    volumes:
      - .:/app

volumes:
  mongo_data:
